@Library("jenkins_library") _

pipeline {
  agent any
  // *** Documentation ***
  // name: test-electron-app-ci
  // description: 'Builds and packages an Electron application using Windows build agent.'
  stages {
    stage ("Install and Test") {
      steps {
        echo "Building...built-in agent"
        sh '''
          hostname
        '''
        // sh '''
        //   cd desktop-app
        //   npm install
          
        // '''
      }
    }

    stage ("Build and Package") {
      agent {
        label 'windows-agent'
      }
      steps {
        echo "Packaging...Windows agent"
        sh '''
          hostname
          cd desktop-app
          npm install
          npm run make
          ls
          cd 
        '''
        dir('desktop-app/out/make/squirrel.windows/x64') {
          stash 'artifacts'
        }
        // TODO: cleanup the agent workspace
      }
    }

    stage ("Archive") {
      steps {
        echo "Archiving...built-in agent"
        sh 'mkdir -p artifacts'
        witthDir('artifacts') {
          unstash 'artifacts'
        }
        sh '''
          ls artifacts
        '''
      }
    }

    stage ("Deploy") {
      steps {
        echo "Packaging...built-in agent"
      }
    }
  }
}
