@Library("jenkins_library") _

pipeline {
  agent any
  // *** Documentation ***
  // name: test-electron-app-ci
  // description: 'Builds and packages an Electron application using Windows build agent.'
  environment {
    BUILD = "${currentBuild.number}";
    // TODO: create the archive name using current build number
  }
  stages {
    stage ("Install and Test") {
      steps {
        echo "Building...built-in agent"
        sh '''
          cd desktop-app
          npm install
          npm run test
        '''
      }
    }

    stage ("Make") {
      agent {
        label 'windows-agent'
      }
      steps {
        echo "Packaging...Windows agent"
        // TODO: parameterize the archive name -- in 7z... command
        sh """
          cd desktop-app
          npm install
          npm run make
          cd out/make/squirrel.windows/x64/
          7z ao ../../../../../test-desktop-app-1.1.0.zip *Setup.exe
        """
        // TODO: parameterize the archive name -- to be more specific in case no clean-up
        stash includes: '*.zip', name: 'installer_archive'
      }
    }

    stage ("Archive") {
      steps {
        echo "Archiving...built-in agent"
        unstash 'installer_archive'
        sh '''
          ls
        '''
        // TODO: next steps to archive the artifact (e.g. Artifactory)
      }
    }

    stage ("Deploy") {
      steps {
        echo "Packaging...built-in agent"
        // TODO: next steps to deploy -- e.g. trigger a CD pipeline or upload directly to S3
      }
    }
  }
}
