@Library("jenkins_library") _

pipeline {
  agent any
  // *** Documentation ***
  // name: test-electron-app-ci
  // description: 'Builds and packages an Electron application using Windows build agent.'
  stages {
    stage ("Install and Test") {
      steps {
        echo "Building...built-in agent"
        // sh '''
        //   cd desktop-app
        //   npm install
        //   npm run test
        // '''
      }
    }

    stage ("Make") {
      agent {
        label 'windows-agent'
      }
      steps {
        echo "Packaging...Windows agent"
        bat '''
          cd desktop-app &&
          npm install &&
          npm run make &&
          rm *.zip &&
          tar -cZf test-desktop-app-1.1.0.zip out/make/squirrel.windows/x64/*Setup.exe
        '''
        stash includes: '*.zip', name: 'installer_archive'
        // clean the workspace
        // sh '''
        //   ls
        //   rm -rf .
        //   ls
        // '''
      }
    }

    stage ("Archive") {
      steps {
        echo "Archiving...built-in agent"
        sh 'mkdir -p artifacts'
        dir('artifacts') {
          unstash 'installer_archive'
        }
        sh '''
          ls artifacts
        '''
        // TODO: next steps to archive the artifact (e.g. Artifactory)
      }
    }

    stage ("Deploy") {
      steps {
        echo "Packaging...built-in agent"
        // TODO: next steps to deploy -- e.g. trigger a CD pipeline or upload directly to S3
      }
    }
  }
}
